filepath: ""
namespace: jx-vault
repositories:
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: banzaicloud-stable/vault-operator
  version: 1.3.0
  name: vault-operator
  forceNamespace: ""
  skipDeps: null
- chart: jx3/vault-instance
  version: 1.0.1
  name: vault-instance
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}